frameworks:
  - name: langchain
    replicaCount: 1
  - name: llamaindex
    replicaCount: 1
  - name: gemini
    replicaCount: 1
  - name: "semantic-kernel"
    replicaCount: 1

LLM_FRAMEWORK: 
DATABASE_ENGINE: 
AZURE_ENDPOINT: ""
AZURE_API_VERSION: ""
AZURE_ENDPOINT_EMBED: ""
AZURE_ENDPOINT_VERSION_EMBED: ""
AZURE_LLM_MODEL: ""
AZURE_LLM_MODEL_EMBED: ""
AZURE_LLM_MODEL_DEPLOYMENT: ""
AZURE_LLM_MODEL_EMBED_DEPLOYMENT: ""
AZURE_API_KEY: ""
AZURE_API_KEY_EMBED: ""
AGENT_IMAGE: 
INGRESS_HOST:
INGRESS_CLASS_NAME:
MONGODB_NAME: 
MONGODB_COLLECTION:
MONGODB_VECTOR_INDEX:
QDRANT_URL:
QDRANT_API_KEY:
QDRANT_COLLECTION_NAME: