apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberag-agent-llamaindex
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frameworks.llamaindex.replicaCount }}
  selector:
    matchLabels:
      app: kuberag-agent-llamaindex
  template:
    metadata:
      labels:
        app: kuberag-agent-llamaindex
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Release.Name }}-secret
            defaultMode: 384
      containers:
      - name: kuberag
        image: {{ .Values.AGENT_IMAGE }}
        env:
        - name: LLM_FRAMEWORK
          value: "llamaindex"
        volumeMounts:
          - name: secret-volume
            mountPath: "/etc/secret-volume"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-cm
        - secretRef:
            name: {{ .Release.Name }}-secret
        ports:
        - containerPort: 5000
