apiVersion: v1
kind: Service
metadata:
  name: kuberag-agent-llamaindex
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: kuberag-agent-llamaindex
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
