apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kuberag-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: kuberag-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.agent.port }}
    targetPort: {{ .Values.service.agent.targetPort }}
    {{- if and (eq .Values.service.type "NodePort") (.Values.service.agent.nodePort) }}
    nodePort: {{ .Values.service.agent.nodePort }}
    {{- end }}
  type: {{ .Values.service.type }}