apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: 'Helm'
    meta.helm.sh/release-namespace: 'default'
data:
  AZURE_ENDPOINT: {{ .Values.AZURE_ENDPOINT }}
  AZURE_API_VERSION: {{ .Values.AZURE_API_VERSION }}
  AZURE_ENDPOINT_EMBED: {{ .Values.AZURE_ENDPOINT_EMBED }}
  AZURE_ENDPOINT_VERSION_EMBED: {{ .Values.AZURE_ENDPOINT_VERSION_EMBED }}
  AZURE_LLM_MODEL: {{ .Values.AZURE_LLM_MODEL }}
  AZURE_LLM_MODEL_EMBED: {{ .Values.AZURE_LLM_MODEL_EMBED }}
  AZURE_LLM_MODEL_DEPLOYMENT: {{ .Values.AZURE_LLM_MODEL_DEPLOYMENT }}
  AZURE_LLM_MODEL_EMBED_DEPLOYMENT: {{ .Values.AZURE_LLM_MODEL_EMBED_DEPLOYMENT }}
  LLM_FRAMEWORK: {{ .Values.LLM_FRAMEWORK }}
  DATABASE_ENGINE: {{ .Values.DATABASE_ENGINE }}
  MONGODB_NAME: {{ .Values.MONGODB_NAME }}
  MONGODB_COLLECTION: {{ .Values.MONGODB_COLLECTION }}
  MONGODB_VECTOR_INDEX: {{ .Values.MONGODB_VECTOR_INDEX }}
  HUGGINGFACE_MODEL:  {{ .Values.HUGGINGFACE_MODEL }}
  QDRANT_URL: {{ .Values.QDRANT_URL }}
  QDRANT_API_KEY: {{ .Values.QDRANT_API_KEY }}
  QDRANT_COLLECTION_NAME: {{ .Values.QDRANT_COLLECTION_NAME }}