apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-{{ .Release.Name }}-ingress
  namespace: {{ .Release.Name }}
spec:
  ingressClassName: {{ .Values.INGRESS_CLASS_NAME }}
  tls:
  - hosts:
      - {{ .Values.INGRESS_HOST }}
    secretName: {{ .Release.Name }}-tls-secret
  rules:
  - host: {{ .Values.INGRESS_HOST }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuberag-agent-langchain
            port:
              number: 80
      - path: /langchain
        pathType: Prefix
        backend:
          service:
            name: kuberag-agent-langchain
            port:
              number: 80
      - path: /llamaindex
        pathType: Prefix
        backend:
          service:
            name: kuberag-agent-llamaindex
            port:
              number: 80
      - path: /gemini
        pathType: Prefix
        backend:
          service:
            name: kuberag-agent-gemini
            port:
              number: 80
      - path: /semantic-kernel
        pathType: Prefix
        backend:
          service:
            name: kuberag-agent-semantic-kernel
            port:
              number: 80