apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-llamaindex
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.INGRESS_CLASS_NAME }}
spec:
  rules:
  - host: {{ .Values.INGRESS_HOST }}
    http:
      paths:
      - path: /llamaindex
        pathType: Prefix
        backend:
          service:
            name: kuberag-agent-llamaindex
            port:
              number: 80
