{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.host .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" .Release.Name) | quote }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: /agent
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-agent-service
                port:
                  number: {{ .Values.service.agent.port | default 80 }}
          - path: /data
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-pipeline-service
                port:
                  number: {{ .Values.service.pipeline.port | default 80 }}
{{- end }}
